apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  labels:
    k8s-app: netshoot
spec:
  replicas: 3
  selector:
    matchLabels:
      name: netshoot
  template:
    metadata:
      labels:
        name: netshoot
    spec:
      containers:
      - name: tcpdump
        image: nicolaka/netshoot
        command: ["sh", "-c", "sleep 1000h"]